name: Javascript Quality Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    name: Lint JS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.*'

      - name: Install npm dependencies
        run: npm install

      - name: Run wp-script lint:js on src folder
        run: npm run lint:js src

      - name: Run wp-script lint:css on src folder
        run: npm run lint:css src